### ISSUE TITLE
Release Status & Tag appropriately

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/pseudonymity-guide#2]
@namcios to reach out to @shannona on the release status of this, and @namcios  do a git tag appropriately. 

See also https://github.com/BlockchainCommons/Community/issues/66

**Comment by namcios** [comment]
Current release status: Edited (v0.9.0) per [/Community issue #66](https://github.com/BlockchainCommons/Community/issues/66). Will do a git tag and release

**Comment by namcios** [comment]
Tagged and released. Closing issue
